package psi.exception;

import psi.model.PsiAlgorithm;

/**
 * This expection is called whenever the UnsupportedKeySize exception is not generated by an external input
 * (e.g, sent by the client) but due to internal errors
 */
public class UnsupportedKeySizeRuntimeException extends RuntimeException {

    public UnsupportedKeySizeRuntimeException(PsiAlgorithm psiAlgorithm, int keySize) {
        super("Key size " + keySize + " is not supported by the algorithm " + psiAlgorithm.toString());
    }
}
