package psi.exception;

import psi.model.PsiAlgorithm;

/**
 * This exception is called whenever the UnsupportedKeySize exception is not generated by an external input
 * (e.g, sent by the client) but due to internal errors. The most relevant example is whenever the server is loading
 * (and not creating) a session associated to an unsupported key size.
 */
public class UnsupportedKeySizeRuntimeException extends RuntimeException {

    public UnsupportedKeySizeRuntimeException(PsiAlgorithm psiAlgorithm, int keySize) {
        super("Key size " + keySize + " is not supported by the algorithm " + psiAlgorithm.toString());
    }
}
